

export default {
    title: 'Calendar',
    numberOfDays: 7,
    timeFormat: 'HH:mma',
    dateTopFormat: 'DD',
    dateBottomFormat: 'ddd',
    hideTime: false,
    progressBar: false,
    showLocation: false,
    showLocationIcon: true,
    hidePastEvents: false,
    showMultiDay: false,
    eventsLimit: 99,
    showEventOrigin: false,
    hideHeader: false,
    highlightToday: false,
    ignoreEventsExpression: '',
    ignoreEventsByLocationExpression: '',
    removeFromEventTitle: '',
    maxHeight: false,
    hardLimit: false,
    hideDeclined: false,
    fullDayEventText: 'All day',
    startText: 'Start',
    endText: 'End',
};
